name: ripple_detection
channels:
- defaults
- conda-forge
dependencies:
- "python >= 3.5"
- "numpy >= 1.11"
- scipy
- "pandas >= 0.18.0"
- matplotlib
- jupyter
- jupyterlab
- nb_conda
- setuptools
- "pytest >= 2.7.1"
- pytest-cov
- coveralls
- flake8
- pip
- pip:
  - 'black[jupyter]'