"""Sharp-wave ripple and multiunit-burst detection from LFP and spikes.

Detectors take ``time``, the signal, ``speed``, and ``sampling_frequency`` and
return one DataFrame row per event; see the README's "Choosing a detector"
table for how they differ, and its "Published parameter values" table for the
range each threshold, duration and smoothing width takes in the literature and
where this package's defaults sit in it.
"""

from ripple_detection.core import (
    DEFAULT_RIPPLE_BAND,
    DEFAULT_TRANSITION_WIDTH,
    NoiseThresholdDiagnostics,
    estimate_noise_threshold,
    exclude_close_events,
    exclude_movement,
    exclude_movement_by_majority,
    exclude_overlap,
    filter_ripple_band,
    gaussian_smooth,
    get_envelope,
    get_multiunit_population_firing_rate,
    histogram_minimum_threshold,
    intersect_intervals,
    intervals_to_mask,
    merge_close_events,
    minimum_sample_count,
    noise_threshold_diagnostics,
    normalize_signal,
    normalize_signal_manually,
    require_inside,
    require_isolation,
    require_overlap,
    require_times_inside,
    require_trace_peak,
    ripple_bandpass_filter,
    sample_count_within,
    segment_boolean_series,
    threshold_by_zscore,
    trim_events_to_trace,
    two_cluster_threshold,
    windows_around_times,
)
from ripple_detection.detectors import (
    Carey_candidate_detector,
    Karlsson_ripple_detector,
    Kay_ripple_detector,
    Long_sharp_wave_ripple_detector,
    Roumis_ripple_detector,
    Shvartsman_ripple_detector,
    Yu_ripple_detector,
    Zugaro_ripple_detector,
    carey_spectral_ripple_score,
    count_spikes_in_events,
    detect_events_from_trace,
    detect_silence_bounded_events,
    get_Kay_ripple_consensus_trace,
    get_Yu_ripple_consensus_trace,
    multiunit_HSE_detector,
    require_active_units,
    state_intervals,
    theta_delta_ratio,
    trim_events_to_spike_windows,
)
from ripple_detection.literature import load_literature_datasets, load_literature_parameters
from ripple_detection.registry import (
    DETECTORS,
    MULTIUNIT,
    RAW_LFP,
    RIPPLE_BAND_LFP,
    DetectorSpec,
    SignalKind,
    get_detector,
)
from ripple_detection.simulate import (
    SimulatedSession,
    brown,
    pink,
    simulate_LFP,
    simulate_multichannel_LFP,
    simulate_multiunit,
    simulate_session,
    simulate_sharp_wave_ripple_pair,
    simulate_speed,
    simulate_theta_delta,
    simulate_time,
    white,
)

try:
    from ripple_detection._version import __version__
except ImportError:
    __version__ = "unknown"

__all__ = [
    "DEFAULT_RIPPLE_BAND",
    "DEFAULT_TRANSITION_WIDTH",
    "DETECTORS",
    "MULTIUNIT",
    "RAW_LFP",
    "RIPPLE_BAND_LFP",
    "Carey_candidate_detector",
    "DetectorSpec",
    "Karlsson_ripple_detector",
    "Kay_ripple_detector",
    "Long_sharp_wave_ripple_detector",
    "NoiseThresholdDiagnostics",
    "Roumis_ripple_detector",
    "Shvartsman_ripple_detector",
    "SignalKind",
    "SimulatedSession",
    "Yu_ripple_detector",
    "Zugaro_ripple_detector",
    "__version__",
    "brown",
    "carey_spectral_ripple_score",
    "count_spikes_in_events",
    "detect_events_from_trace",
    "detect_silence_bounded_events",
    "estimate_noise_threshold",
    "exclude_close_events",
    "exclude_movement",
    "exclude_movement_by_majority",
    "exclude_overlap",
    "filter_ripple_band",
    "gaussian_smooth",
    "get_Kay_ripple_consensus_trace",
    "get_Yu_ripple_consensus_trace",
    "get_detector",
    "get_envelope",
    "get_multiunit_population_firing_rate",
    "histogram_minimum_threshold",
    "intersect_intervals",
    "intervals_to_mask",
    "load_literature_datasets",
    "load_literature_parameters",
    "merge_close_events",
    "minimum_sample_count",
    "multiunit_HSE_detector",
    "noise_threshold_diagnostics",
    "normalize_signal",
    "normalize_signal_manually",
    "pink",
    "require_active_units",
    "require_inside",
    "require_isolation",
    "require_overlap",
    "require_times_inside",
    "require_trace_peak",
    "ripple_bandpass_filter",
    "sample_count_within",
    "segment_boolean_series",
    "simulate_LFP",
    "simulate_multichannel_LFP",
    "simulate_multiunit",
    "simulate_session",
    "simulate_sharp_wave_ripple_pair",
    "simulate_speed",
    "simulate_theta_delta",
    "simulate_time",
    "state_intervals",
    "theta_delta_ratio",
    "threshold_by_zscore",
    "trim_events_to_spike_windows",
    "trim_events_to_trace",
    "two_cluster_threshold",
    "white",
    "windows_around_times",
]
