name: PR Test

on: push

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  #, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for hatch-vcs to determine version from git tags
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ripple_detection
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - name: Install ripple_detection
      shell: bash -l {0}
      run: |
        pip install -e .[dev,examples]
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest --cov=ripple_detection tests/
    - name: Test notebooks
      shell: bash -l {0}
      run: |
        jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute examples/detection_examples.ipynb
        jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute examples/test_individual_algorithm_components.ipynb
